print ('Agendamento de Consulta')
print ('Preencha os campos abaixo:')
input ('Nome: ')
input ('Peso: ')
input ('Altura: ')
idade = input ('Idade: ')
input ('Consulta Marcada ou Emergencia? ')
input ('Genero: ')
input ('Telefone: ')
input ('Data de hoje: ')
input ('Caso tenha útero, existe a possibilidade de gravidez? ')
input ('Caso tenha útero quando foi a sua ultima menstruação?: ')
input ('Quais sintomas você está sentindo: ')
input ('Você possui alguma patologia? Se sim qual?' )
input ('Teve covid resentemente (menos de 6 meses)?' )
input ('Você tem tomado algum medicamento? Se sim qual? ')