print ('Agendamento de Consulta')
print ('Preencha os campos abaixo:')
input ('Nome: ')
input ('Sobrenome: ')
input ('Cor/Raça: ')
print ('Homem ou mulher cis são pessoas que se identificam com o gênero (homem ou mulher) que lhes foi atribuído ao nascer. Homem ou mulher trans são pessoas que se identificam com um gênero diferente do que foi designado no momento de seu nascimento.')
input ('Genero: ')
input ('CPF: ')
input ('Data de Nasciento: ')
input ('Nome da mãe: ')
print ('Aguarde o processamento dos dados...')